# Тут указывается используемый в проекте язык программирования, можно указать несколько
language: python

# Далее, укажите версии python для которых нужно производить сборки
python:
  - "3.7"

# Параметры окружения
env:
  - PyQt5=12.7.0

# Команда для установки зависимостей в окружение (при этом доступны переменные из секции "env")
install:
  - pip install -q PyQt5==$PyQt5_VERSION
  - pip install -r requirements.txt --use-mirrors

# Команда для запуска тестов, в моем случае они запускаются именно так
#script: python multi_sessions/tests.py