# Тут указывается используемый в проекте язык программирования, можно указать несколько
language: python

# Далее, укажите версии python для которых нужно производить сборки
python:
  - "3.6"
  - "3.7"
  - "3.8"

# Параметры окружения
env:
  - PyQt5, pytest

# Команда для установки зависимостей в окружение (при этом доступны переменные из секции "env")
install:
  - pip install -q PyQt5
  - pip install -q pytest
#  - pip install -q pytest-qt
#  - pip install -r requirements.txt --use-mirrors

# Команда для запуска тестов, в моем случае они запускаются именно так
script: python -m pytest test.py